version: '3.8'

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        VARIANT: "16"
    links:
      - db
    expose:
      - 4200
    volumes:
      - ./client/workspace:/workspace:cached
    command: sleep infinity

  server:
    build:
      context: server
      dockerfile: Dockerfile
      args:
        VARIANT: "6.0"
    expose:
      - 4000
    volumes:
      - ./server/workspace:/workspace:cached
    command: sleep infinity
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    links:
      - client
      - server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data: null

networks:
  internal: null